version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "lenta"
      POSTGRES_USER: "django_"
      POSTGRES_PASSWORD: "mS54Z%55JNs1B4Z5xUxY3JIL@nYz"
    ports:
      - "5432:5432/tcp"
      - "5432:5432/udp"